version: '3'

volumes:
  data:
    external:
      name: ${docker_volume_name}

services:
  cross_dev_orange:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - workspace=/develop/
        - persist_data=${persist_data}
    volumes:
      - data:${persist_data}
    
